; Menu configuration file
; File location: $moddir/addons/amxmodx/configs/cmds.ini
; To use with Commands Menu plugin

; NOTE: By default in all settings the access level is set to "u".
;       However you can change that, to limit the access to some settings.

; Commands Menu: ; < description > < command > < flags > < access level >
; "a" - execute from server console
; "b" - execute from admin console
; "c" - execute on all clients
; "d" - back to menu when executed

; Game Modes
"Vanilla Mode"		"exec vanilla.cfg"	"a"	"u"
"GunGame Mode"		"exec gg.cfg"		"a"	"u"
"Deathmatch Mode"	"exec dm.cfg"		"a"	"u"
"Competitive Mode"	"exec comp.cfg"		"a"	"u"
"KZ Mode"		"exec kz.cfg"		"a"	"u"
"Surf Mode"		"exec surf.cfg"		"a"	"u"
" "		"-"			""	"u"
; Server
"Restart Round"	"sv_restartround 1"	"a"	"u"
"Pause"			"amx_pause"		"ad"	"u"
"Friendly Fire ON"	"mp_friendlyfire 1"	"a"	"u"
"Friendly Fire OFF"	"mp_friendlyfire 0"	"a"	"u"
